apiVersion: v1
kind: Service
metadata:
  name: yuki-agent
  namespace: yuki
  labels:
    app.kubernetes.io/name: yuki
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: yuki
    app.kubernetes.io/component: api
